### ISSUE TITLE
Start from PHP Image

### ISSUE THREAD

**Issue by leonfilser** [Admidio/docker#7]
### Not an issue but a suggestion:

I think it is easier to start the Dockerfile with "FROM php:7.2-apache" instead of "FROM debian:jessie" so you dont need the whole setup part for Apache and PHP.

I will attach the files i created so you can see what i mean. Feel free to use them or ask me any questions about the code.

**Dockerfile:**
```
FROM php:7.2-apache

RUN apt-get update \
    && apt-get install git -y \
    && docker-php-ext-install pdo_mysql \
    && git clone https://github.com/Admidio/admidio.git --branch=v3.3.11 /var/www/html \
    && chown -R www-data:www-data /var/www/html

EXPOSE 80
```

**Docker Compose:**

```
version: '3.5'

services:
  admidio:
    build: .
    image: admidio:v3.3.11
    restart: always
    container_name: admidio
    ports:
      - "80:80"
    volumes:
      - $DOCKER_DATA/admidio/files:/var/www/admidio/adm_my_files
      - $DOCKER_DATA/admidio/themes:/var/www/admidio/adm_themes
      - $DOCKER_DATA/admidio/plugins:/var/www/admidio/adm_plugins

```
